"use client";
import {useEffect,useMemo,useState} from "react";
const symbols=["NIFTY 50","BANKNIFTY","RELIANCE","TCS","INFY","HDFCBANK"];
export default function Home(){
 const [symbol,setSymbol]=useState("NIFTY 50"); const [live,setLive]=useState(false); const [connected,setConnected]=useState(false); const [last,setLast]=useState<number|null>(null); const [analysis,setAnalysis]=useState<any>(null); const status=useMemo(()=>connected?"LIVE STREAM CONNECTED":live?"LIVE GATE ARMED":"PAPER MODE",[connected,live]);
 useEffect(()=>{ if(!live)return; const base=process.env.NEXT_PUBLIC_QUANTPULSE_WS_URL; if(!base)return; const ws=new WebSocket(base); ws.onopen=()=>{setConnected(true);ws.send(JSON.stringify({type:"subscribe",symbol,timeframe:"1m"}));}; ws.onclose=()=>setConnected(false); ws.onerror=()=>setConnected(false); ws.onmessage=e=>{try{const p=JSON.parse(e.data);if(p.type==="candle"&&p.symbol===symbol){setLast(Number(p.close));if(p.analysis)setAnalysis(p.analysis);}}catch{}}; return()=>{ws.close();setConnected(false);setAnalysis(null)};},[live,symbol]);
 return <main><header><div><b>⚡ QuantPulse</b><span> Market Intelligence Terminal</span></div><div className="status">{status}</div></header>
 <section className="hero"><div><p className="eyebrow">TRADING PLATFORM</p><h1>Market intelligence, signals & risk — in one terminal.</h1><p className="muted">Provider-fed OHLCV streaming, deterministic technical analysis, pattern detection and risk controls. Paper trading remains the default.</p></div><div className="gate"><button onClick={()=>setLive(!live)}>{live?"Disable live stream":"Connect live stream"}</button><small>Live execution is separately locked. A market-data WebSocket URL must be configured by the deployment.</small></div></section>
 <nav>{symbols.map(s=><button className={s===symbol?"active":""} onClick={()=>setSymbol(s)} key={s}>{s}</button>)}</nav>
 <section className="grid"><article className="chart"><div className="cardhead"><div><strong>{symbol}</strong><div className="muted">5m • provider-fed market structure</div></div><div className="liveDot">{connected?"● LIVE":"○ DISCONNECTED"}</div></div><div className="chartbox"><div className="price">{last?last.toFixed(2):"—"}</div><div className="empty">{connected?"Waiting for the next validated OHLCV candle…":"Connect an authorized real-time market-data provider to stream candles here."}</div></div></article>
 <aside><div className="signal"><p>AI FUSION SIGNAL</p><h2>{analysis?.signal ?? "WAITING FOR ANALYSIS"}</h2><div className="confidence">{analysis?`${analysis.confidence}%`: "—"}</div><span>Confidence is model strength, not profit probability.</span></div><div className="risk"><p>RISK ENGINE</p><div>Entry <b>{last?last.toFixed(2):"—"}</b></div><div>Stop loss <b>{analysis?.stop_loss ?? "—"}</b></div><div>Target <b>{analysis?.target ?? "—"}</b></div><div>R:R <b>{analysis?.risk_reward ?? "—"}</b></div></div></aside></section>
 <section className="cards"><div><b>Trend Engine</b><span>{analysis?`${analysis.trend} • EMA9 ${analysis.ema9} / EMA21 ${analysis.ema21}`:"Waiting for candles"}</span></div><div><b>Pattern Scanner</b><span>{analysis?.pattern ?? "Waiting for candles"}</span></div><div><b>News Intelligence</b><span>Neutral until a licensed news provider is connected</span></div><div><b>Paper Trading</b><span>Persistent orders + P&amp;L</span></div></section><footer>QuantPulse is analytical software. Signals are not guaranteed returns or profit probabilities. Real-money execution remains locked until security, broker authorization and risk controls are independently verified.</footer></main>
}